#This file stores configuration options for Iris, such as the currently active shaderpack
#Tue Oct 06 17:34:06 GMT-03:00 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=32
shaderPack=BSL_v10.1.3.zip
